name: Update Claude Code Documentation

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Fetch latest documentation
      id: fetch-docs
      run: |
        python fetch_claude_docs.py || echo "fetch_failed=true" >> $GITHUB_OUTPUT
      continue-on-error: true
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        git diff --exit-code || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A docs/
        git add docs_manifest.json
        git commit -m "Update Claude Code documentation - $(date +'%Y-%m-%d')"
        git push
    
    - name: Create issue on failure
      if: steps.fetch-docs.outputs.fetch_failed == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const date = new Date().toISOString().split('T')[0];
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Documentation update failed - ${date}`,
            body: `The automated documentation update failed on ${date}.\n\nPlease check the [workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`,
            labels: ['bug', 'automation']
          })